import groovy.json.JsonSlurper

pluginManagement {
    repositories {
		maven {
            name = "tr7zw-proxy"
            url "https://maven.tr7zw.dev/repository/maven-public/"
        }
        gradlePluginPortal()
    }
}


plugins {
    id("dev.kikugie.stonecutter") version "${stonecutter_version}"
}

stonecutter {
	kotlinController = true
    centralScript = "error.gradle"

    create(getRootProject()) {

		def settings = new JsonSlurper().parseText(file('versions.json').text)
		for (String ver : settings.versions) {
			def scriptName = "versions/1.8.9-forge/build.gradle.kts"
			version("$ver","$ver".split("-")[0]).buildscript(scriptName)
		}

		// Fixed at 1.8.9-forge
		vcsVersion = "1.8.9-forge"
    }
}

rootProject.name = "$id$"